AWSTemplateFormatVersion: '2010-09-09' # Versão do formato do template CloudFormation

Parameters:
  BucketName:
    Type: String
    Description: Nome do bucket S3 a ser criado
    Default: projeto-devops-pucrs-2025

Resources:
  MeuBucketS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: Private # Somente usuários autenticados da conta podem acessar

      PublicAccessBlockConfiguration: # Bloqueia qualquer acesso público
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

      VersioningConfiguration:
        Status: Enabled # Habilita versionamento de objetos
      
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred

      Tags:
        - Key: Ambiente
          Value: Producao
        - Key: Projeto
          Value: Fase-1
        - Key: Owner
          Value: Christian
        - Key: StackName
          Value: !Ref AWS::StackName

  PoliticaLeituraPublica:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MeuBucketS3
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: LeituraPublica
            Effect: Allow
            Principal: "*" # Permite qualquer identidade, mas com condição
            Action: "s3:GetObject"  # só leitura
            Resource: !Sub "${MeuBucketS3.Arn}/*"  # objetos dentro do bucket

Outputs:
  NomeDoBucket:
    Description: "Nome do bucket S3"
    Value: !Ref MeuBucketS3
